# ==============================================================================
# 🎨 CATPPUCCIN MOCHA (fond profond « Crust »)
# Changer de thème à la volée : Ctrl+Maj+F12 (kitten themes)
# ==============================================================================
foreground              #CDD6F4
background              #11111B
selection_foreground    #11111B
selection_background    #F5E0DC

cursor                  #F5E0DC
cursor_text_color       #11111B
cursor_trail_color      #CBA6F7

url_color               #89B4FA

active_border_color     #CBA6F7
inactive_border_color   #313244
bell_border_color       #F9E2AF
visual_bell_color       none

# Barre d'onglets
active_tab_foreground   #11111B
active_tab_background   #CBA6F7
inactive_tab_foreground #A6ADC8
inactive_tab_background #1E1E2E
tab_bar_background      #11111B

# Marques (Ctrl+Maj+M)
mark1_foreground        #11111B
mark1_background        #B4BEFE
mark2_foreground        #11111B
mark2_background        #CBA6F7
mark3_foreground        #11111B
mark3_background        #74C7EC

# Barre de défilement
scrollbar_handle_color  #CBA6F7

# 16 couleurs ANSI (les « bright » un peu plus vives que les normales)
color0  #45475A
color8  #585B70
color1  #F38BA8
color9  #F57799
color2  #A6E3A1
color10 #89D88B
color3  #F9E2AF
color11 #EBD391
color4  #89B4FA
color12 #74A8FC
color5  #F5C2E7
color13 #F2AEDE
color6  #94E2D5
color14 #6BD7CA
color7  #BAC2DE
color15 #A6ADC8
# Couleurs étendues utilisées par certains programmes
color16 #FAB387
color17 #F5E0DC
